// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp1XdUP8xyr1Jq9PM4RcHhiQtdIODM-u4',
    appId: '1:1072648248508:web:05b8314bfd31e71546c4b9',
    messagingSenderId: '1072648248508',
    projectId: 'fnfproj-3a611',
    authDomain: 'fnfproj-3a611.firebaseapp.com',
    storageBucket: 'fnfproj-3a611.firebasestorage.app',
    measurementId: 'G-WVWPXDP96H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHGtAthqIRvRydOJ9quPoBdkZ9gh9kGfo',
    appId: '1:1072648248508:android:6be6acd01a6edcb446c4b9',
    messagingSenderId: '1072648248508',
    projectId: 'fnfproj-3a611',
    storageBucket: 'fnfproj-3a611.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASjsOCeUXNKmwsuTPy9qZtdgb6ZbmaXM8',
    appId: '1:1072648248508:ios:a5a2036c790ecbcc46c4b9',
    messagingSenderId: '1072648248508',
    projectId: 'fnfproj-3a611',
    storageBucket: 'fnfproj-3a611.firebasestorage.app',
    iosBundleId: 'com.example.fnf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASjsOCeUXNKmwsuTPy9qZtdgb6ZbmaXM8',
    appId: '1:1072648248508:ios:a5a2036c790ecbcc46c4b9',
    messagingSenderId: '1072648248508',
    projectId: 'fnfproj-3a611',
    storageBucket: 'fnfproj-3a611.firebasestorage.app',
    iosBundleId: 'com.example.fnf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp1XdUP8xyr1Jq9PM4RcHhiQtdIODM-u4',
    appId: '1:1072648248508:web:0e13031f211e548246c4b9',
    messagingSenderId: '1072648248508',
    projectId: 'fnfproj-3a611',
    authDomain: 'fnfproj-3a611.firebaseapp.com',
    storageBucket: 'fnfproj-3a611.firebasestorage.app',
    measurementId: 'G-8Y4TFVQHWK',
  );
}
